import type { Metadata } from "next";
import fontLocal from "next/font/local";
import "./globals.css";

const myFont = fontLocal({
  src: "../public/fonts/Raleway-VariableFont_wght.ttf",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>{children}</body>
    </html>
  );
}
